import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Form from "../component/js-form"
import { Box, Heading, Text } from '@chakra-ui/react'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>AI Chat Bot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Box p="10" maxW='80%'width={600} borderWidth='1px' borderRadius='lg' overflow='hidden'>
          <Heading as='h1' size='lg' mb={5}>AI Chat Bot</Heading>
          <Form />
        </Box>
      </main>
    </div>
  );
}


