import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Form from "../component/form"
import { Box, Heading } from '@chakra-ui/react'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title id="title">OpenAI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Box bg="rgba(255,255,255,0.3)" p="10" maxW='80%'width={600} borderRadius='lg' overflow='hidden'>
          <Heading as='h1' size='lg' mb={5}>Play with OpenAI</Heading>
          <Form />
        </Box>
      </main>
    </div>
  );
}


