import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Input from '../component/Input'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>AI Chat Bot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Input />
        <h2>Responses</h2>
        <p>
          This will be an array that will push newest response submitted by the
          user to the top and push down the old responses.
        </p>
        <p>
          This will consist of Prompt: Response: and put in the designated
          values to these answers
          <br></br>
          Components? collect data from array (when submitting) and present
          info of prompt and response and display on main page
          <br></br>
          Psudo Code: const post = prompt, response ( prompt: blah blah blah,
          response: I'm an AI that's smart! ),
          <br></br>
          prompt: blah blah blah, response: I'm an AI that's smart! )
          <br></br>
          collect string and .push to array display array
        </p>
        <h3>First Step: Get data from what's submitted from the user!</h3>
        <h3>Second Step: Post user's submission on page</h3>
      </main>
    </div>
  );
}
